# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: net_messages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='net_messages.proto',
  package='aytabu.core',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x12net_messages.proto\x12\x0b\x61ytabu.core\"\xad\x01\n\nClientInfo\x12\n\n\x02id\x18\x01 \x02(\x03\x12\x0c\n\x04name\x18\x02 \x02(\t\x12\x1a\n\x12\x62irth_date_seconds\x18\x03 \x02(\r\x12.\n\x03sex\x18\x04 \x02(\x0e\x32!.aytabu.core.ClientInfo.ClientSex\"9\n\tClientSex\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x08\n\x04MALE\x10m\x12\n\n\x06\x46\x45MALE\x10\x66\x12\t\n\x05OTHER\x10o\"2\n\x0cServerConfig\x12\x12\n\nnum_fields\x18\x01 \x02(\r\x12\x0e\n\x06\x66ields\x18\x02 \x03(\t\"\xd0\x04\n\x0cUserSnapshot\x12\x11\n\ttimestamp\x18\x01 \x02(\x04\x12,\n\x04pose\x18\x02 \x02(\x0b\x32\x1e.aytabu.core.UserSnapshot.Pose\x12.\n\x05\x63olor\x18\x03 \x02(\x0b\x32\x1f.aytabu.core.UserSnapshot.Image\x12.\n\x05\x64\x65pth\x18\x04 \x02(\x0b\x32\x1f.aytabu.core.UserSnapshot.Image\x12\x34\n\x08\x66\x65\x65lings\x18\x05 \x02(\x0b\x32\".aytabu.core.UserSnapshot.Feelings\x1a.\n\x0bTranslation\x12\t\n\x01x\x18\x01 \x02(\x02\x12\t\n\x01y\x18\x02 \x02(\x02\x12\t\n\x01z\x18\x03 \x02(\x02\x1a\x36\n\x08Rotation\x12\t\n\x01x\x18\x01 \x02(\x02\x12\t\n\x01y\x18\x02 \x02(\x02\x12\t\n\x01z\x18\x03 \x02(\x02\x12\t\n\x01w\x18\x04 \x02(\x02\x1a\x34\n\x05Image\x12\x0e\n\x06height\x18\x01 \x02(\r\x12\r\n\x05width\x18\x02 \x02(\r\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x1ax\n\x04Pose\x12:\n\x0btranslation\x18\x01 \x02(\x0b\x32%.aytabu.core.UserSnapshot.Translation\x12\x34\n\x08rotation\x18\x02 \x02(\x0b\x32\".aytabu.core.UserSnapshot.Rotation\x1aQ\n\x08\x46\x65\x65lings\x12\x0e\n\x06hunger\x18\x01 \x02(\x02\x12\x0e\n\x06thirst\x18\x02 \x02(\x02\x12\x12\n\nexhaustion\x18\x03 \x02(\x02\x12\x11\n\thappiness\x18\x04 \x02(\x02')
)



_CLIENTINFO_CLIENTSEX = _descriptor.EnumDescriptor(
  name='ClientSex',
  full_name='aytabu.core.ClientInfo.ClientSex',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MALE', index=1, number=109,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FEMALE', index=2, number=102,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OTHER', index=3, number=111,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=152,
  serialized_end=209,
)
_sym_db.RegisterEnumDescriptor(_CLIENTINFO_CLIENTSEX)


_CLIENTINFO = _descriptor.Descriptor(
  name='ClientInfo',
  full_name='aytabu.core.ClientInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='aytabu.core.ClientInfo.id', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='aytabu.core.ClientInfo.name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='birth_date_seconds', full_name='aytabu.core.ClientInfo.birth_date_seconds', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sex', full_name='aytabu.core.ClientInfo.sex', index=3,
      number=4, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CLIENTINFO_CLIENTSEX,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=209,
)


_SERVERCONFIG = _descriptor.Descriptor(
  name='ServerConfig',
  full_name='aytabu.core.ServerConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_fields', full_name='aytabu.core.ServerConfig.num_fields', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fields', full_name='aytabu.core.ServerConfig.fields', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=211,
  serialized_end=261,
)


_USERSNAPSHOT_TRANSLATION = _descriptor.Descriptor(
  name='Translation',
  full_name='aytabu.core.UserSnapshot.Translation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='aytabu.core.UserSnapshot.Translation.x', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='aytabu.core.UserSnapshot.Translation.y', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='aytabu.core.UserSnapshot.Translation.z', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=495,
  serialized_end=541,
)

_USERSNAPSHOT_ROTATION = _descriptor.Descriptor(
  name='Rotation',
  full_name='aytabu.core.UserSnapshot.Rotation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='aytabu.core.UserSnapshot.Rotation.x', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='aytabu.core.UserSnapshot.Rotation.y', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='aytabu.core.UserSnapshot.Rotation.z', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='w', full_name='aytabu.core.UserSnapshot.Rotation.w', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=543,
  serialized_end=597,
)

_USERSNAPSHOT_IMAGE = _descriptor.Descriptor(
  name='Image',
  full_name='aytabu.core.UserSnapshot.Image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='height', full_name='aytabu.core.UserSnapshot.Image.height', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='width', full_name='aytabu.core.UserSnapshot.Image.width', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='aytabu.core.UserSnapshot.Image.data', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=599,
  serialized_end=651,
)

_USERSNAPSHOT_POSE = _descriptor.Descriptor(
  name='Pose',
  full_name='aytabu.core.UserSnapshot.Pose',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='translation', full_name='aytabu.core.UserSnapshot.Pose.translation', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rotation', full_name='aytabu.core.UserSnapshot.Pose.rotation', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=653,
  serialized_end=773,
)

_USERSNAPSHOT_FEELINGS = _descriptor.Descriptor(
  name='Feelings',
  full_name='aytabu.core.UserSnapshot.Feelings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hunger', full_name='aytabu.core.UserSnapshot.Feelings.hunger', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='thirst', full_name='aytabu.core.UserSnapshot.Feelings.thirst', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='exhaustion', full_name='aytabu.core.UserSnapshot.Feelings.exhaustion', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='happiness', full_name='aytabu.core.UserSnapshot.Feelings.happiness', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=775,
  serialized_end=856,
)

_USERSNAPSHOT = _descriptor.Descriptor(
  name='UserSnapshot',
  full_name='aytabu.core.UserSnapshot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='aytabu.core.UserSnapshot.timestamp', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pose', full_name='aytabu.core.UserSnapshot.pose', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='color', full_name='aytabu.core.UserSnapshot.color', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='depth', full_name='aytabu.core.UserSnapshot.depth', index=3,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='feelings', full_name='aytabu.core.UserSnapshot.feelings', index=4,
      number=5, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_USERSNAPSHOT_TRANSLATION, _USERSNAPSHOT_ROTATION, _USERSNAPSHOT_IMAGE, _USERSNAPSHOT_POSE, _USERSNAPSHOT_FEELINGS, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=264,
  serialized_end=856,
)

_CLIENTINFO.fields_by_name['sex'].enum_type = _CLIENTINFO_CLIENTSEX
_CLIENTINFO_CLIENTSEX.containing_type = _CLIENTINFO
_USERSNAPSHOT_TRANSLATION.containing_type = _USERSNAPSHOT
_USERSNAPSHOT_ROTATION.containing_type = _USERSNAPSHOT
_USERSNAPSHOT_IMAGE.containing_type = _USERSNAPSHOT
_USERSNAPSHOT_POSE.fields_by_name['translation'].message_type = _USERSNAPSHOT_TRANSLATION
_USERSNAPSHOT_POSE.fields_by_name['rotation'].message_type = _USERSNAPSHOT_ROTATION
_USERSNAPSHOT_POSE.containing_type = _USERSNAPSHOT
_USERSNAPSHOT_FEELINGS.containing_type = _USERSNAPSHOT
_USERSNAPSHOT.fields_by_name['pose'].message_type = _USERSNAPSHOT_POSE
_USERSNAPSHOT.fields_by_name['color'].message_type = _USERSNAPSHOT_IMAGE
_USERSNAPSHOT.fields_by_name['depth'].message_type = _USERSNAPSHOT_IMAGE
_USERSNAPSHOT.fields_by_name['feelings'].message_type = _USERSNAPSHOT_FEELINGS
DESCRIPTOR.message_types_by_name['ClientInfo'] = _CLIENTINFO
DESCRIPTOR.message_types_by_name['ServerConfig'] = _SERVERCONFIG
DESCRIPTOR.message_types_by_name['UserSnapshot'] = _USERSNAPSHOT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClientInfo = _reflection.GeneratedProtocolMessageType('ClientInfo', (_message.Message,), dict(
  DESCRIPTOR = _CLIENTINFO,
  __module__ = 'net_messages_pb2'
  # @@protoc_insertion_point(class_scope:aytabu.core.ClientInfo)
  ))
_sym_db.RegisterMessage(ClientInfo)

ServerConfig = _reflection.GeneratedProtocolMessageType('ServerConfig', (_message.Message,), dict(
  DESCRIPTOR = _SERVERCONFIG,
  __module__ = 'net_messages_pb2'
  # @@protoc_insertion_point(class_scope:aytabu.core.ServerConfig)
  ))
_sym_db.RegisterMessage(ServerConfig)

UserSnapshot = _reflection.GeneratedProtocolMessageType('UserSnapshot', (_message.Message,), dict(

  Translation = _reflection.GeneratedProtocolMessageType('Translation', (_message.Message,), dict(
    DESCRIPTOR = _USERSNAPSHOT_TRANSLATION,
    __module__ = 'net_messages_pb2'
    # @@protoc_insertion_point(class_scope:aytabu.core.UserSnapshot.Translation)
    ))
  ,

  Rotation = _reflection.GeneratedProtocolMessageType('Rotation', (_message.Message,), dict(
    DESCRIPTOR = _USERSNAPSHOT_ROTATION,
    __module__ = 'net_messages_pb2'
    # @@protoc_insertion_point(class_scope:aytabu.core.UserSnapshot.Rotation)
    ))
  ,

  Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), dict(
    DESCRIPTOR = _USERSNAPSHOT_IMAGE,
    __module__ = 'net_messages_pb2'
    # @@protoc_insertion_point(class_scope:aytabu.core.UserSnapshot.Image)
    ))
  ,

  Pose = _reflection.GeneratedProtocolMessageType('Pose', (_message.Message,), dict(
    DESCRIPTOR = _USERSNAPSHOT_POSE,
    __module__ = 'net_messages_pb2'
    # @@protoc_insertion_point(class_scope:aytabu.core.UserSnapshot.Pose)
    ))
  ,

  Feelings = _reflection.GeneratedProtocolMessageType('Feelings', (_message.Message,), dict(
    DESCRIPTOR = _USERSNAPSHOT_FEELINGS,
    __module__ = 'net_messages_pb2'
    # @@protoc_insertion_point(class_scope:aytabu.core.UserSnapshot.Feelings)
    ))
  ,
  DESCRIPTOR = _USERSNAPSHOT,
  __module__ = 'net_messages_pb2'
  # @@protoc_insertion_point(class_scope:aytabu.core.UserSnapshot)
  ))
_sym_db.RegisterMessage(UserSnapshot)
_sym_db.RegisterMessage(UserSnapshot.Translation)
_sym_db.RegisterMessage(UserSnapshot.Rotation)
_sym_db.RegisterMessage(UserSnapshot.Image)
_sym_db.RegisterMessage(UserSnapshot.Pose)
_sym_db.RegisterMessage(UserSnapshot.Feelings)


# @@protoc_insertion_point(module_scope)
