version: "3.3"
services:
    server:
        image: doccortex:0.1.29
        environment:
            - SHARED_STORAGE=/cortex_storage
        command: ['scripts/wait_for_it.sh', '-h', 'mq', '-p', '5672', '--', 'python', '-m', 'cortex.server', 'run-server', 'rabbitmq://mq:5672', '--host=0.0.0.0', '--port=8080']
        ports:
            - "8080:8080"
            - "8000:8000"
        depends_on:
            - parser
            - saver
            - mq
        volumes:
            - ./cortex_storage:/cortex_storage
    parser:
        environment:
            - SHARED_STORAGE=/cortex_storage
        image: doccortex:0.1.29
        command:   ['scripts/wait_for_it.sh', '-h', 'mq', '-p', '5672', '--', 'python', '-m', 'cortex.parser', 'start-all', 'rabbitmq://mq:5672']
        depends_on:
            - mq

        volumes:
            - ./cortex_storage:/cortex_storage
    saver:
        environment:
            - SHARED_STORAGE="/cortex_storage"
        image: doccortex:0.1.29
        command:  ['scripts/wait_for_it.sh', '-h', 'mq', '-p', '5672', '--',
                   'scripts/wait_for_it.sh', '-h', 'db', '-p', '27017', '--',
                   'python', '-m', 'cortex.saver', 'run-saver', 'mongodb://db:27017', 'rabbitmq://mq:5672']
        depends_on:
            - mq
            - db
        volumes:
            - ./cortex_storage:/cortex_storage
    api:
        environment:
            - SHARED_STORAGE=/cortex_storage
        image: doccortex:0.1.29
        command:  ['scripts/wait_for_it.sh', '-h', 'db', '-p', '27017', '--', 'python', '-m', 'cortex.api', 'run-server', '-h','0.0.0.0', '-p', '5000', '-d', 'mongodb://db:27017']
        depends_on:
            - db
        ports:
            - "5000:5000"
        volumes:
            - ./cortex_storage:/cortex_storage
    mq:
        image: rabbitmq:3
        ports:
            - 5672:5672

    db:
        image: mongo:4
        ports:
            - 27017:27017
